insert into mod_sistema.modulo ("nombre", "esquema", "es_base") values 
('Módulo de administración', 'mod_administracion', true),
('Módulo del sistema', 'mod_sistema', true),
('Módulo de compras', 'mod_compras', false),
('Módulo de CRM', 'mod_crm', false),
('Módulo de facturación', 'mod_facturacion', false),
('Módulo de finanzas', 'mod_finanzas', false),
('Módulo de gestión humana', 'mod_gestion_humana', false),
('Módulo de invetario', 'mod_inventario', false),
('Módulo de logística', 'mod_logistica', false),
('Módulo de nomina', 'mod_nomina', false),
('Módulo de proveedores', 'mod_proveedores', false),
('Módulo de proyectos', 'mod_proyectos', false),
('Módulo de ventas', 'mod_ventas', false);

insert into mod_sistema.acceso_tipo ("nombre") values
('Menú'),
('Sub menú'),
('Vista'),
('Pestaña');

insert into mod_sistema.permiso_tipo ("nombre") values
('Ver'),
('Crear'),
('Actualizar'),
('Eliminar');

insert into mod_sistema.ubicacion_tipo ("nombre") values 
('Pais'),
('Departamento'),
('Estado'),
('Provincia'),
('Condado'),
('Ciudad'),
('Municipio'),
('Corregimiento'),
('Vereda'),
('Comuna'),
('Barrio'),
('Localidad'),
('Distrito'),
('Región'),
('Territorio'),
('Isla'),
('Parroquia'),
('Zona'),
('Sector'),
('Aldea'),
('Pueblo'),
('Villa'),
('Caserío'),
('Hacienda'),
('Finca'),
('Ranchería'),
('Resguardo Indígena'),
('Área Protegida'),
('Zona Franca'),
('Zona Industrial'),
('Urbanización'),
('Conjunto Residencial'),
('Asentamiento Informal'),
('Colonia'),
('Cantón'),
('Manzana'),
('Lote'),
('Edificio'),
('Bloque'),
('Apartamento');

INSERT INTO mod_sistema.ubicacion (nombre, tipo_id) VALUES 
('Colombia', 1),
('Antioquia', 2),
('Bogotá D.C.', 2),
('Caldas', 2),
('Valle del Cauca', 2),
('Atlántico', 2),
('Sucre', 2),
('Nariño', 2),
('Cundinamarca', 2),
('Medellín', 2),
('Manizales', 4),
('Cali', 5),
('Barranquilla', 6),
('Sincelejo', 7),
('Pasto', 8),
('Bogotá D.C.', 9),
('Bogotá (Cundinamarca)', 9);
